name: graphland-dgl
channels:
  - pytorch
  - nvidia
  - dglteam/label/th24_cu124
dependencies:
  - python=3.11
  - pip=24.2
  - setuptools=68
  - tqdm=4.66
  - pyyaml=6
  - pydantic=2.5
  - numpy=1.26
  - pandas=2.2
  - scikit-learn=1.5
  - mkl=2023.1
  - pytorch=2.5.1
  - pytorch-cuda=12.4
  - torchdata=0.7
  - torchtriton=3.1
  - dgl=2.4
  - pip:
      - torch_geometric==2.5
      - ogb==1.3.6
      - optuna==4.3
